version: '3.1'
services:
  app-cache:
    restart: 'always'
    image: 'localhost:5000/kanga-cache:latest'
    ports:
      - "8885:8085"
    container_name: 'kanga-cache'
    command: ["java", "-Dfile.encoding=UTF-8", "-jar", "kanga-cache.jar"]